// Code generated by protoc-gen-go.
// source: chat.proto
// DO NOT EDIT!

/*
Package chat is a generated protocol buffer package.

It is generated from these files:
	chat.proto

It has these top-level messages:
	Register
	Login
	Logout
	ChatMsg
*/
package chat

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Register struct {
	Service []string `protobuf:"bytes,1,rep,name=service" json:"service,omitempty"`
}

func (m *Register) Reset()                    { *m = Register{} }
func (m *Register) String() string            { return proto.CompactTextString(m) }
func (*Register) ProtoMessage()               {}
func (*Register) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Login struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Addr string `protobuf:"bytes,2,opt,name=addr" json:"addr,omitempty"`
}

func (m *Login) Reset()                    { *m = Login{} }
func (m *Login) String() string            { return proto.CompactTextString(m) }
func (*Login) ProtoMessage()               {}
func (*Login) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type Logout struct {
	Addr string `protobuf:"bytes,1,opt,name=addr" json:"addr,omitempty"`
}

func (m *Logout) Reset()                    { *m = Logout{} }
func (m *Logout) String() string            { return proto.CompactTextString(m) }
func (*Logout) ProtoMessage()               {}
func (*Logout) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type ChatMsg struct {
	Name string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Msg  string   `protobuf:"bytes,2,opt,name=msg" json:"msg,omitempty"`
	From string   `protobuf:"bytes,3,opt,name=from" json:"from,omitempty"`
	To   []string `protobuf:"bytes,4,rep,name=to" json:"to,omitempty"`
}

func (m *ChatMsg) Reset()                    { *m = ChatMsg{} }
func (m *ChatMsg) String() string            { return proto.CompactTextString(m) }
func (*ChatMsg) ProtoMessage()               {}
func (*ChatMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func init() {
	proto.RegisterType((*Register)(nil), "chat.Register")
	proto.RegisterType((*Login)(nil), "chat.Login")
	proto.RegisterType((*Logout)(nil), "chat.Logout")
	proto.RegisterType((*ChatMsg)(nil), "chat.ChatMsg")
}

func init() { proto.RegisterFile("chat.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 174 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x6c, 0x8f, 0x3b, 0x0e, 0xc2, 0x30,
	0x10, 0x44, 0x95, 0x0f, 0x09, 0xd9, 0x02, 0x21, 0x57, 0x2e, 0x28, 0x50, 0x44, 0x91, 0x0a, 0x0a,
	0x8e, 0x40, 0x1b, 0x9a, 0x70, 0x02, 0x93, 0x18, 0xc7, 0x85, 0xb3, 0xc8, 0x5e, 0x38, 0x3f, 0x5a,
	0x07, 0x10, 0x05, 0xdd, 0xf3, 0xbc, 0xd1, 0xc8, 0x0b, 0xd0, 0x8f, 0x8a, 0xf6, 0x77, 0x8f, 0x84,
	0x22, 0x67, 0xae, 0x77, 0xb0, 0xec, 0xb4, 0xb1, 0x81, 0xb4, 0x17, 0x12, 0xca, 0xa0, 0xfd, 0xd3,
	0xf6, 0x5a, 0x26, 0xdb, 0xac, 0xa9, 0xba, 0xcf, 0xb3, 0x3e, 0xc0, 0xa2, 0x45, 0x63, 0x27, 0x21,
	0x20, 0x9f, 0x94, 0x63, 0x9f, 0x34, 0x55, 0x17, 0x99, 0x33, 0x35, 0x0c, 0x5e, 0xa6, 0x73, 0xc6,
	0x5c, 0x6f, 0xa0, 0x68, 0xd1, 0xe0, 0x83, 0xbe, 0x36, 0xf9, 0xb1, 0x17, 0x28, 0x4f, 0xa3, 0xa2,
	0x73, 0x30, 0x7f, 0x07, 0xd7, 0x90, 0xb9, 0x60, 0xde, 0x7b, 0x8c, 0xdc, 0xba, 0x79, 0x74, 0x32,
	0x9b, 0x5b, 0xcc, 0x62, 0x05, 0x29, 0xa1, 0xcc, 0xe3, 0x47, 0x53, 0xc2, 0x6b, 0x11, 0xcf, 0x3a,
	0xbe, 0x02, 0x00, 0x00, 0xff, 0xff, 0xf3, 0x60, 0x40, 0x6e, 0xe4, 0x00, 0x00, 0x00,
}
